### ISSUE TITLE
Need Proper error handling on sign in when 3 required conditions are not met

### ISSUE THREAD

**Issue by Wizardofoddz** [ComputeforCancer/app#1]
When signing in, with FB or new user and one of the 3 conditions to start computing is not met (i.e. not plugged in to power, wifi, battery level) the user gets the following error message: 
"There have been problems attaching to scientific project:" 

This should display the error condition that is not met. 
The error above causes confusion. 

![screenshot_20170128-153733](https://cloud.githubusercontent.com/assets/11368906/22401139/c526450e-e58e-11e6-9531-49b342fe41c6.png)

**Comment by smartgammadev** [comment]
this is native Boinc error message, it means that there have been internal problems attaching world community grid project, what message should we display, please provide with the correct one.

**Comment by Wizardofoddz** [comment]
This is been Fixed and committed.
