### ISSUE TITLE
Login: Password is overlapped by other form fields

### ISSUE THREAD

**Issue by Wizardofoddz** [ComputeforCancer/app#2]
Login: Password is overlapped by other form fields in landscape. 
The form field above cut off the password text. Trivial cosmetic defect. 

![screenshot_20170128-150051](https://cloud.githubusercontent.com/assets/11368906/22401161/a3d71c88-e58f-11e6-8859-eaf527b5dd6e.png)

**Comment by smartgammadev** [comment]
will be fixed

**Comment by Wizardofoddz** [comment]
No longer an issue
