### ISSUE TITLE
Milestone: Fire OS app

### ISSUE THREAD

**Issue by Wizardofoddz** [ComputeforCancer/app#4]
Pending Milestone Fire OS app

**Comment by smartgammadev** [comment]
task is not clear, provide with additional info

**Comment by Wizardofoddz** [comment]
This was implemented in April 22nd Live on all Amazon Fire devices
https://www.amazon.com/ComputeforCancer-Compute-For-Cancer/dp/B06Y4CW3Y5/ref=sr_1_1?ie=UTF8&qid=1494204336&sr=8-1&keywords=computeforcancer

**Comment by Wizardofoddz** [comment]
Completed
